services:
#    exact_online.example:
#        class: aibianchi\ExactOnlineBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # exact_online.manager:
    #     class: aibianchi\ExactOnlineBundle\Manager\ExactManager
    #     arguments: ['@doctrine.orm.entity_manager']

    exact_online.rest_api:
        class: aibianchi\ExactOnlineBundle\Manager\ExactJsonApi
        arguments: ['@doctrine.orm.entity_manager']

    exact_online.xml_api:
        class: aibianchi\ExactOnlineBundle\Manager\ExactXmlApi
        arguments: ['@doctrine.orm.entity_manager']


    exact_online.exceptionlistener:
        class: aibianchi\ExactOnlineBundle\Event\ExceptionListener
        arguments: ['@monolog.logger.exactAPI']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: exactAPI }
