services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: true

    exact_online.rest_api:
        class: ExactOnlineBundle\Manager\ExactJsonApi
        arguments: ['@doctrine.orm.entity_manager']

    exact_online.xml_api:
        class: ExactOnlineBundle\Manager\ExactXmlApi
        arguments: ['@doctrine.orm.entity_manager']

    ExactOnlineBundle\Command\ExactSyncCommand:
        tags:
            - { name: 'console', command: 'exact:token:refresh' }

    exact_online.manager:
        class: ExactOnlineBundle\Manager\ExactManager
        arguments: ['@doctrine.orm.entity_manager']

    exact_online.exceptionlistener:
        class: ExactOnlineBundle\Event\ExceptionListener
        arguments: ['@monolog.logger.exactAPI']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: exactAPI }

    ExactOnlineBundle\Manager\ExactManager: '@exact_online.manager'
